### ISSUE TITLE
unit tests through many errors

### ISSUE THREAD

**Issue by KatharinaHoff** [tomasbruna/miniprot-boundary-scorer#1]
Hi Tomas,

great work, thank you!

The unit tests throw a large number of errors. Here's a screenshot of the bottom:
![image](https://user-images.githubusercontent.com/39333668/222151298-fb1d4066-cff4-4a4d-89d3-452b619920c6.png)

I will continue to test functionality (without the unit tests) :-)

**Comment by KatharinaHoff** [comment]
Tested, it works as expected, I think. Here's my output:

```
Warning: A stop codon detected inside protein 34740_0:001d0a at al. position 45432
Warning: A stop codon detected inside protein 34740_0:001d0a at al. position 45432
error: Could not read matrix file
Warning: score for (.,a) is not defined in the matrix. Returning -4 instead.
Warning: score for (a,.) is not defined in the matrix. Returning -4 instead.
Warning: score for ( ,a) is not defined in the matrix. Returning -4 instead.
===============================================================================
All tests passed (1165 assertions in 5 test cases)```

**Comment by xiekunwhy** [comment]
Hi,

Why Warning "A stop codon detected inside protein" ? They are abnormal? miniprothint need stop_codon, but stop_codon is empty

here are my commad line 
`miniprot -t 10 --aln -P Dda --outn 1 -j 1 -G 1000000 Par.ref.mpi Par.Dda.fa > Par.hom.aln`
`miniprot_boundary_scorer -o Par.hom.gff -s blosum62.csv < Par.hom.aln`
which printed a lot of \"Warning: A stop codon detected inside protein ...\"

but when I ran miniprothint 
`python miniprothint.py --workdir hints Par.hom.gff`
But I got errors
[Thu May 11 00:04:04 2023] error: exited due to an error in command: grep stop_codon Par.hom.gff | grep proteinEnd=1 /path/to/hints/tmp/stopsAllEnd10nl2a0g.gff

obviously, miniprothint.py need stop_codons, but why miniprot_boundary_scorer delete them?

Best,
Kun

**Comment by tomasbruna** [comment]
Hi Kun,

are there stop codons (stars) at the ends of proteins in your `Par.Dda.fa` input? I actually never tested that scenario -- the parser may not be handling that well; I will work on a fix this weekend.

If that's the case, you can remove those trailing stars for now as a workaround.

Tomas

**Comment by tomasbruna** [comment]
Interesting. Ideally, it should not matter whether the trailing stars are at the protein ends.

Would you mind sharing your inputs with me so that I can debug this issue on your example? You can contact me by email (bruna.tomas@gmail.com) if you don't want to share that publicly.

**Comment by xiekunwhy** [comment]
Sure, I testing the whole pipeline again, I will send you all datas when the testing is finished.

**Comment by xiekunwhy** [comment]
Hi Tomas,

Datas have been send to bruna.tomas@gmail.com with title "About miniprothints".

All command lines are in cmd.sh file, I think miniprothint.py loss stop_codon when generating hints/miniprot.gtf.
`
## miniprot mapping, -P not works here
miniprot -t 10 --aln -P Dda --outn 1 -j 1 -G 1000000 Par.ref.fa Par.Dda.fa > ./02.mapping/Par.Dda.aln
miniprot -t 10 --aln -P Hzo --outn 1 -j 1 -G 1000000 Par.ref.fa Par.Hzo.fa > ./02.mapping/Par.Hzo.aln
miniprot -t 10 --aln -P Sja --outn 1 -j 1 -G 1000000 Par.ref.fa Par.Sja.fa > ./02.mapping/Par.Sja.aln
miniprot -t 10 --aln -P Tal --outn 1 -j 1 -G 1000000 Par.ref.fa Par.Tal.fa > ./02.mapping/Par.Tal.aln
miniprot -t 10 --aln -P Tma --outn 1 -j 1 -G 1000000 Par.ref.fa Par.Tma.fa > ./02.mapping/Par.Tma.aln

## cat
cat 02.mapping/*.aln > Par.hom.aln

## score
miniprot_boundary_scorer -o Par.hom.gff -s ./blosum62.csv < Par.hom.aln

## hints
python miniprothint.py --workdir hints Par.hom.gff --ignoreCoverage

## find train
python ./GALBA/scripts/find_train_candidates.py -m hints/miniprot.gtf -o hints/train.gtf

## check
# all transcripts in hints/train.gtf
grep -w transcript hints/train.gtf|wc -l
20932

# keep transcripts which with final stop codon and without in-frame stop codon
gffread -J -T -g Par.ref.fa hints/train.gtf -o train.J.gtf
grep -w transcript train.J.gtf|wc -l
2

# keep transcripts which without in-frame stop codon
gffread -V -T -g Par.ref.fa hints/train.gtf -o train.V.gtf
grep -w transcript train.V.gtf|wc -l
17972

# it means only 2 transcripts with final stop codon and without in-frame stop codon,
# 17972 without in-frame stop codon, 2960 with in-frame

## 
gffread -J -T -g Par.ref.fa hints/miniprot.gtf -o miniprot.J.gtf
grep -w transcript miniprot.J.gtf|wc -l
35

`

Best,
Kun
